# Generated by Django 5.0 on 2024-01-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_complexity_alter_task_est_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Family', 'Family'), ('Work', 'Work'), ('Finance', 'Finance'), ('Education', 'Education'), ('Personal', 'Personal'), ('Career', 'Career'), ('Social', 'Social'), ('HouseholdErrands', 'Household Errands'), ('Entertainment', 'Entertainment'), ('Others', 'Others')], max_length=20),
        ),
    ]
