# Generated by Django 5.0 on 2024-02-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_time',
        ),
        migrations.AlterField(
            model_name='task',
            name='complexity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='est_completion',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(default=1),
        ),
    ]
